behaviors:
  MLDriver:
    trainer_type: ppo
    time_horizon: 128
    summary_freq: 10000
    max_steps: 10.0e5
    hyperparameters:
      batch_size: 128
      beta: 1e-3
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.99
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_epoch: 3
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 64
        use_recurrent: false
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

  MLDriverDemo:
    trainer_type: ppo
    time_horizon: 128
    summary_freq: 10000
    max_steps: 10.0e5
    hyperparameters:
      batch_size: 128
      beta: 1e-3
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.99
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_epoch: 3
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 64
        use_recurrent: false
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.5
        demo_path: "C:/Users/Ryan McLarty/Documents/Unity Projects/ML-Drivers/Assets/Demonstrations/MLDriver.demo"
    behavioral_cloning:
      strength: 0.5
      demo_path: "C:/Users/Ryan McLarty/Documents/Unity Projects/ML-Drivers/Assets/Demonstrations/MLDriver.demo"
